name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  DOCKER_IMAGE_NAME: bocan/hugo

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Write Docker config.json for Harbor
        env:
          REG: registry.cloudcauldron.io
          U: ${{ secrets.HARBOR_USERNAME }}
          P: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          set -e
          mkdir -p "$HOME/.docker"
          auth=$(printf '%s' "$U:$P" | base64 -w0 2>/dev/null || printf '%s' "$U:$P" | base64)
          cat > "$HOME/.docker/config.json" <<EOF
          { "auths": { "$REG": { "auth": "$auth" } } }
          EOF
          jq . "$HOME/.docker/config.json"

      # 2) Explicit docker CLI login (works the same as the action, but clearer errors)
      - name: Docker CLI login to Harbor
        env:
          REG: registry.cloudcauldron.io
          U: ${{ secrets.HARBOR_USERNAME }}
          P: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          set -euxo pipefail
          printf %s "$P" | docker --debug login "$REG" -u "$U" --password-stdin

      - name: Probe Harbor /v2/ from runner
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          set -euxo pipefail
          echo "Unauthenticated probe (expect 401):"
          curl -sS -D - -o /dev/null https://registry.cloudcauldron.io/v2/ || true
          echo "Authenticated probe (expect 200):"
          curl -sS -u "${HARBOR_USER}:${HARBOR_PASS}" -D - -o /dev/null https://registry.cloudcauldron.io/v2/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Cloud Cauldron Harbor
        uses: docker/login-action@v3
        with:
          registry: registry.cloudcauldron.io
          ecr: false
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          sbom: true
          provenance: mode=max
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:build-cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:build-cache,mode=max
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      # --- Signing section ---
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Set IMAGE digest ref
        run: echo "IMAGE_REF=${{ env.DOCKER_IMAGE_NAME }}@${{ steps.build.outputs.digest }}" >> $GITHUB_ENV

      - name: Cosign sign image (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"   # enable keyless
        run: |
          cosign sign --yes "${IMAGE_REF}"

      # ---- Generate & attest a signed SBOM (SPDX JSON) ----
      - name: Generate SBOM (SPDX JSON) for linux/amd64
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_REF }}
          platform: linux/amd64
          format: spdx-json
          output-file: sbom-amd64.spdx.json

      - name: Cosign attest SBOM (in-toto)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign attest --yes --type spdx --predicate sbom-amd64.spdx.json "${IMAGE_REF}"

      - name: Verify image signature
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/${{ github.repository }}/.github/workflows/.*@${{ github.ref }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            "${IMAGE_REF}"

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
